# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac901a626f9cfe4519bed40a01c0ac2781a74aaf4d7a64fd1f31946738173df6fa7b8c59ebe46785fa44d3cf9f5bd909e448e56d924ae205d17b5b5701b43059

test:
  secret_key_base: a53b4e914442a30fd7ad48f49ffb92eefcc6c2b0b4030a7e09f33e37416a12ee97e27ac892affd8d88a113fec4d816cba6c4ef91a592f452161091e2dd4ab0f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
