# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aaf5dfce5a293a59c416619ae067e71236a0c12034dd5748a5b7e0bf89a78f18804914783a147b9fac490802951d861ec703984450dcba101d8088bc81d2dad

test:
  secret_key_base: 8b74c3c1c4de334c0f70548becff2625fe4c5d385829c459327778d37cd42102a779ffc5d9a045979976d2b63d3eb079a757c55a9da0f959f670b3139bb0a057

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
