# A sample Gemfile
source "https://rubygems.org"

gem "sinatra"
gem "sinatra-activerecord"
gem "rake"
gem "activerecord"
gem "pg"
gem "tux", "~>0.3.0"

# gem 'activerecord-sortable'
# gem 'jquery-ui-sinatra'

# gem "rails"
