# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2157d0dd7bed3a86d79c080b01fb6c4e19a742ce062873a1e33cf91823dba914779da3dc77f805aaccbd796024e945a3e60c758238c15289782e24a9ae9ca0fc

test:
  secret_key_base: 78dc08833dff6b35fb34cfcc7b989bfb073692fef35b99f9126434b738fdbd08b98b4788e996b32225808380566fb5cb0c03e4de4facc10aab76fc91b1ae20ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
