# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 164729e032b22f739ee26c8c1b636355fa20b11fe22a086ea980d4d3967bf0c53f2c1f799523d831f9882f53d339081217032afbcad021fc824e7904b30c5cc1

test:
  secret_key_base: ed33bf8168805d2ca8527e157ac63128986824f64f17b624019ab6455b4551800b9350486ae1b41e9cc6052e458054d67ff550df0795b38f212ded3b34b931ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
