# A sample Gemfile
source "https://rubygems.org"
gem "sinatra"
gem "sinatra-activerecord" #allows us to use Sinatra with ActiveRecord  
gem "rake" #gives us tasks and dependencies that can be specified in standard Ruby syntax (don't worry about it if you don't get it)
gem "activerecord" #gives us all the excellent class methods you see above (and more) and allows for object relational mapping
gem "pg" #allows us to use postgresql as a DBMS for our app
gem "tux" #allows us to have an interactive shell to play with object creation
gem "hirb"